
package traductor;

import Clases.Lexico;
import Clases.Sintactico;
//import com.sun.istack.internal.logging.Logger;
import java.io.StringReader;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author Romilio
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(jIngles, "src/imgs/espanol.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jEspanol, "src/imgs/ingles.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jB_salir = new javax.swing.JButton();
        jB_Borrar = new javax.swing.JButton();
        jB_Traducir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_ingles = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_espaniol = new javax.swing.JTextPane();
        jIngles = new javax.swing.JLabel();
        jEspanol = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_salir.setBackground(new java.awt.Color(204, 0, 0));
        jB_salir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB_salir.setForeground(new java.awt.Color(255, 255, 255));
        jB_salir.setText("X");
        jB_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salirActionPerformed(evt);
            }
        });
        jPanel2.add(jB_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jB_Borrar.setBackground(new java.awt.Color(0, 0, 102));
        jB_Borrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB_Borrar.setForeground(new java.awt.Color(255, 255, 255));
        jB_Borrar.setText("Limpiar");
        jB_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BorrarActionPerformed(evt);
            }
        });
        jPanel2.add(jB_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 120, -1));
        jB_Borrar.getAccessibleContext().setAccessibleName("Borrar");

        jB_Traducir.setBackground(new java.awt.Color(0, 0, 102));
        jB_Traducir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jB_Traducir.setForeground(new java.awt.Color(255, 255, 255));
        jB_Traducir.setText("Traducir");
        jB_Traducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_TraducirActionPerformed(evt);
            }
        });
        jPanel2.add(jB_Traducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jScrollPane2.setViewportView(jt_ingles);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 30));

        jt_espaniol.setToolTipText("");
        jt_espaniol.setName(""); // NOI18N
        jScrollPane1.setViewportView(jt_espaniol);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 220, 30));
        jPanel2.add(jIngles, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 220, 90));
        jIngles.getAccessibleContext().setAccessibleName("jIngles");

        jPanel2.add(jEspanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 90));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("Let’s Talk");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BorrarActionPerformed
        // TODO add your handling code here:
        this.jt_espaniol.setText("");
        this.jt_ingles.setText("");
    }//GEN-LAST:event_jB_BorrarActionPerformed

    private void jB_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por utilizar Let’s Talk");
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jB_salirActionPerformed

    private void jB_TraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_TraducirActionPerformed
        // TODO add your handling code here:
        String strinToBeParsed = jt_ingles.getText();
        StringReader reade = new StringReader(strinToBeParsed);
        try{
            jt_espaniol.removeAll();
            this.jt_espaniol.setText("");
            Lexico lexer = new Lexico(reade);
            Sintactico anasintac = new Sintactico(lexer);
            anasintac.parse();
            Traducir s = new Traducir();
            String respuesta = "";
            respuesta = s.afirmati;
            jt_espaniol.setText(respuesta);
            respuesta = "";
        }
        catch(Exception ex){
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_TraducirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Borrar;
    private javax.swing.JButton jB_Traducir;
    private javax.swing.JButton jB_salir;
    private javax.swing.JLabel jEspanol;
    private javax.swing.JLabel jIngles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jt_espaniol;
    private javax.swing.JTextPane jt_ingles;
    // End of variables declaration//GEN-END:variables
}
